### ISSUE TITLE
How can I download the MyST corpus

### ISSUE THREAD

**Issue by YuXiangLin1234** [amphionspace/SD-Eval#1]
Hello,

Thank you for developing such a meaningful benchmark. I am currently conducting experiments using this benchmark but encountered an issue when trying to request access to the MyST corpus. The link provided in the README (https://boulderlearning.com/resources/request-the-myst-corpus/) does not seem to include a working contact method for the corpus owner. The "Contact Us" page on the website returns a 404 error, and the licensor's email appears to be undeliverable.

How I may proceed to obtain access to the MyST dataset?

**Comment by Ajyy** [comment]
Hi,
﻿
Thanks for your interest. We download MyST from here https://catalog.ldc.upenn.edu/LDC2021S05, and it should be free for research purposes.

**Comment by YuXiangLin1234** [comment]
I see. Thank you for your assistance!

**Comment by rublear** [comment]
Hello, I am trying to access the MyST dataset, but it seems that the page was deleted because I get:
"The page you were looking for doesn't exist."

Could you please provide guidance?
